name: Node.js CI

on:
  push:
    branches: [ bot ]
  pull_request:
    branches: [ bot ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.3.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn 
    - run: yarn run lint
