name: Node.js CI   

on:
  push:
    branches: [ bot ]
  pull_request:
    branches: [ bot ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn 
      name: Install dependencies
  
    - run: yarn lint
      name: lint JS and JSON code

    - run: yarn build
      name: Build TS code
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/bot') && (github.repository == 'choppymaster/sphynx')
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: docker/setup-buildx-action@v2
      name: Setup Docker BuildX system
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      name: Deploy the image
      with:
        push: true
        tags: choppymaster/sphynx:latest
